services:
  bun_server:
    build : .
    ports : 
      - 3000:3000
    environment:
      - LISTEN=true
      - POSTGRES_URL=postgresql://postgres:postgres@database:5432/postgres
      - AUTH0_DOMAIN=dev-25r4jfrx2w3std4k.us.auth0.com
      - AUTH0_AUDIENCE=mathapi
      - JWT_TEST=j
    volumes:
     - ./src:/home/bun/app/src
  database:
    image : postgres:18.3@sha256:7e32e9833a6fb1c92c32552794cb6ed569d51b445a54907d35fc112ef39684db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432
  cache:
    image : redis:8-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    volumes:
      - ./redis:/data
