services:
  bun_server:
    build : .
    ports : 
      - 3000:3000
    environment:
      - LISTEN=true
      - POSTGRES_URL=postgresql://postgres:postgres@database:5432/postgres
      - AUTH0_DOMAIN=dev-25r4jfrx2w3std4k.us.auth0.com
      - AUTH0_AUDIENCE=mathapi
      - JWT_TEST=j
      - SUPABASE_URL=https://wjifwflztejubvgibbtj.supabase.co
      - S3_BASE=http://localhost:9324/
    volumes:
     - ./src:/home/bun/app/src
     - ./image:/home/bun/app/image
  database:
    image : postgres:18.4@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - 5432:5432
  cache:
    image : redis:8-alpine@sha256:81b6f81d6a6c5b9019231a2e8eb10085e3a139a34f833dcc965a8a959b040b72
    volumes:
      - ./redis:/data
  fs_daemon:
    build:
      context: ./fs_daemon
    volumes:
      - ./image:/image
    ports:
      - "9324:8000"
